[Issue 285] Alphabetize Playlists in PlaylistsCmd
jagrosh/MusicBot pull request #1024
Opened 2021-11-06 23:45 UTC by morrisj95

### This pull request...
  - [ ] Fixes a bug
  - [x] Introduces a new feature
  - [ ] Improves an existing feature
  - [x] Boosts code quality or performance

### Description

This appears to be not an issue on many systems, as files are already alphabetized and playlists are stored in files.  This PR enforces alphabetization via sort.

Additionally, this PR deduplicates a several lines of code shared between `PlaylistCmd` and `PlaylistsCmd`.

This is all contained in just 2 commits for step-by-step review.

![image](https://user-images.githubusercontent.com/36784267/140627025-cc870e03-f582-416b-85e1-bff8cb7fb8ba.png)

#### Why add that system property?

Unit testing logs were very bloated if you try to make them pure with `@Before`/`@After`.  This is an alternative to introducing a `serversettings.file` property since that was a complex change.

The unit tests were abandoned due to excessive complexity not worth it for the simplicity of this feature.  But here's what I had built.

![image](https://user-images.githubusercontent.com/36784267/140627026-7ec7a200-dc3c-4ddc-8e29-2014f79424fe.png)

![testUnit1](https://user-images.githubusercontent.com/36784267/140626939-20e3de5f-659f-49d9-9b04-e23b395cbf5e.JPG)

### Purpose
Replace this with a description of the problem or use-case

### Relevant Issue(s)
This PR closes issue #285

2021-11-07 00:21 UTC, morrisj95 commented
Looks like the build failure is appveyor trying to call an invalid URL.

2021-12-03 08:13 UTC, MichailiK requested changes

2021-12-03 08:13 UTC, MichailiK commented on src/main/java/com/jagrosh/jmusicbot/settings/SettingsManager.java
> +                return;
This seems to be out of scope of this pull request. Personally, I would prefer if this change were to be made in a new pull request.

2021-12-03 08:13 UTC, MichailiK commented on src/main/java/com/jagrosh/jmusicbot/commands/owner/PlaylistCmd.java
> +            new PlaylistsCmd(bot).replyList(event, false);
Do not instantiate a new instance of a command every time. Make the `replyList` method static & update the arguments to include the playlist loader.
```suggestion
            PlaylistsCmd.replyList(event, bot.getPlaylistLoader(), false);
```

2021-12-03 08:13 UTC, MichailiK commented on src/main/java/com/jagrosh/jmusicbot/commands/music/PlaylistsCmd.java
> +    public void replyList(CommandEvent event, boolean showInstructions)
Make this method static & update the arguments to include the playlist loader.
```suggestion
    public static void replyList(CommandEvent event, PlaylistLoader loader, boolean showInstructions)
```

2021-12-04 04:10 UTC, morrisj95 commented on src/main/java/com/jagrosh/jmusicbot/commands/music/PlaylistsCmd.java
> +            if (showInstructions) {
Formatting styles standardized in both of my open PRs.  I will push the `static` method changes after I've had a chance to compile & test that it still functions properly.

2021-12-20 16:45 UTC, closed without merging