Allow configurable default skip ratio
jagrosh/MusicBot pull request #1140
Opened 2022-04-01 00:38 UTC by t3rminus

### This pull request...
  - [ ] Fixes a bug
  - [X] Introduces a new feature
  - [ ] Improves an existing feature
  - [ ] Boosts code quality or performance

### Description
Allows the server owner to configure the skip ratio in config.txt, including disabling vote-related messages if skip ratio is 0

### Purpose
Useful for owners being able to set a default ratio. Setting to "0" and having no vote-related messages is also helpful for well-behaved, or small servers, where music playing is mostly co-operative, and people may want to skip troll songs or livestreams that have gone on too long.

2022-04-06 07:04 UTC, MichailiK requested changes
As this currently stands, this can lead to behavior which users might not expect, when changing the skip ratio in the config. I would suggest to instead use negative numbers (like -1) to indicate that a guild has not specified a skip ratio. The `skip` command could then determine whether to use the skip ratio of the guild or the bot.

2022-04-06 07:04 UTC, MichailiK commented on src/main/java/com/jagrosh/jmusicbot/settings/SettingsManager.java
> +        return new Settings(this, 0, 0, 0, 100, null, RepeatMode.OFF, null, this.config.getSkipRatio());
This should be updated to use a negative number.

2022-04-06 07:04 UTC, MichailiK commented on src/main/java/com/jagrosh/jmusicbot/settings/SettingsManager.java
> +    public SettingsManager(BotConfig config)
Any references to the `BotConfig` in this class should become unnecessary, once my suggestions are applied. Please remove them.

2022-04-06 07:10 UTC, MichailiK commented
Lastly, [`src/main/resources/reference.conf`](https://github.com/jagrosh/MusicBot/blob/master/src/main/resources/reference.conf) needs to be updated, adding the new option to the bot config.

2023-03-22 20:05 UTC, t3rminus commented
I've made the changes you suggested.

2024-02-28 20:13 UTC, MichailiK approved these changes
Whoops, I didn't notice I haven't reviewed & approved this. My apologies for that! Jagrosh will have another look at this, I'm hoping we can get this merged & into the next release very soon.

2024-03-02 00:42 UTC, merged