added blacklist command
jagrosh/MusicBot pull request #1229
Opened 2022-10-09 16:06 UTC by Osanchez

### This pull request...
  - [ ] Fixes a bug
  - [X] Introduces a new feature
  - [ ] Improves an existing feature
  - [ ] Boosts code quality or performance

### Description
Intended for servers who do not want to go through the hassle of configuring music bot roles. a new command for bot owners has been added that allows them to blacklist users from using music commands. 

### Purpose
Servers that want to give access to the music bot commands without role configuration, allows the bot owner to add or remove users from a blacklist that will be checked upon music command.

2022-10-09 20:00 UTC, MichailiK requested changes
Hello, thanks a lot for your contribution! This would be a great & convenient alternative to using `settc` and changing the the text channel's permissions. However, I have some thoughts regarding how this feature (as it currently stands) fits into JMusicBot & issues regarding the code.

Some users might want to whitelist members, not blacklist. They might attempt to blacklist all their members & any members that might join. That's confusing & very poor UX. It feels half-finished as it stands. I believe that, in order to make this feature feel complete, there needs to be functionality that:

- Can turn this list between off, white & black
- Perhaps also add/remove roles to it

Until then, I don't think this should be released to the public as it stands.

There are some issues regarding the code as well. The large problem I see is that the blacklist entries get stored as mention strings, instead of just IDs. Once that changes, I'll review the code & point out all minor issues.

<hr>

If you've got any questions or need help, you can ask here or [join the Discord server](https://discord.gg/0p9LSGoRLu6Pet0k) and ask me over there (Michaili#1397).

If you believe that you can't fulfil these feature requests & fixes, no hard feelings. This is quite a lot to ask from someone who isn't too familiar with this code base. I can merge this into a feature branch & continue work from there myself.

2022-10-09 20:40 UTC, jagrosh commented
I'm frankly not a fan of this feature at all, as I think that utilizing Discord permissions is the correct way to manage control of the bot. In general, I think if something is possible using native Discord tools, having the bot handle it in a divergent way is confusing, leads to unnecessary inconsistency between multiple bots, and feels messy in the codebase.

2022-10-10 01:46 UTC, Osanchez commented
@jagrosh I agree with MichailiK that this needs to have both a blacklist and white list to work effectively. You are saying that native discord permissions should fully control permissions but this does not cover use case for people who are hosting the bot for a friend and do not have role management permission. Let’s say you want to create a single role for using bot commands. You are sort of forcing users to create DJ, music bot roles exclusively for the bot. I agree it’s cleaner to handle this way, but this change in no way prevents users from continuing to use this functionality thus considered a new feature.

2022-10-10 23:27 UTC, Osanchez commented
@MichailiK added whitelist. user can enable disable whitelist/black list with setlist command <list_type> <action>
eg. !setlist whitelist enable

this will require uses to be added to a whitelist to use music commands
eg. !whitelist add @user

I have slightly changed code to parse user ID from mention.

2022-10-10 23:29 UTC, Osanchez commented
I believe added role to this will be easy to implement. I may or may not include in this PR depending on if you feel its needed.

2022-10-11 10:39 UTC, MichailiK commented
> I may or may not include in this PR depending on if you feel its needed.

Yes, include it with this PR.

2022-10-11 11:42 UTC, MichailiK requested changes
After having a quick glance, it looks like you are able to enable both a white list & black list. I think such a use case is too rare. There should be one list, which you can toggle between off, black & white.

I'm thinking of just having 2 or 3 commands, one for setting the list type & to add/remove users or roles to it. I'm indecisive on how these should be named. Currently, the word "usage" comes to my mind: 

- `?setusagelist <off|allow|deny>`
- `?addusage <@user>`
- `?removeusage <@user>` (or perhaps combine both commands to add/remove a user?)

These names are not too ideal, I am still thinking about this (suggestions are welcome) but I would stick to 1 list which can be toggled between off/black/white. You're welcome to implement these while we're coming up with how to call these commands.

I've spotted some minor issues skimming through the code that should be fixed:

2022-10-11 11:42 UTC, MichailiK commented on src/main/java/com/jagrosh/jmusicbot/commands/owner/BlacklistUserCmd.java
> +            event.reply(event.getClient().getError()+" Please include a user");
Please use `replyError`/`replyWarning`/`replySuccess` instead. Older JMusicBot code used to do this, as these utility methods haven't existed back then.

Make this change across all `reply`'s you've added as well.

```suggestion
            event.replyError("Please include a user");
```

2022-10-11 13:41 UTC, Osanchez commented on src/main/java/com/jagrosh/jmusicbot/JMusicBot.java
> +                        new SetPermissionListSettingsCmd(bot)
hey @MichailiK, you cannot toggle both lists at the same time. I have a check to prevent both from being enabled.

2022-10-11 13:48 UTC, Osanchez commented on src/main/java/com/jagrosh/jmusicbot/commands/owner/BlacklistUserCmd.java
> +        this.guildOnly = false;
moved all commands to admin commands, also set guild only to true on all commands.

2022-10-11 13:48 UTC, Osanchez commented on src/main/java/com/jagrosh/jmusicbot/commands/owner/BlacklistUserCmd.java
> +public class BlacklistUserCmd extends OwnerCommand
same as comment below, now is guild only command and have been changed to an admin command.

2022-10-11 13:49 UTC, Osanchez commented on src/main/java/com/jagrosh/jmusicbot/JMusicBot.java
> +                        new SetPermissionListSettingsCmd(bot)
moved command registration to correct admin command block and sorted alphabetically.

2022-10-11 13:51 UTC, Osanchez commented
working on adding permissions, also want to know if only creating one list is a must. I almost want to suggest we keep both lists separated because they are not alike and unless we clear the list upon switching it will be a hassle for users to re-configure.

2022-10-11 20:04 UTC, Osanchez commented
@MichailiK I have refactored code to be a single list. user can set this list as whitelist or blacklist. admin can add users or roles to this list

2022-10-11 22:32 UTC, jagrosh commented
I am going to reiterate that I don't think this feature is the right fit for this bot, as our current goals are to make things simpler overall, not more complex. Additionally, this doesn't even seem to solve the initially-proposed problem, which was allowing the bot owner to manage who can use the bot; as it stands, this is a per-guild setting that requires being in the guild to set, and thus doesn't solve anything that couldn't be solved via channel permissions.

2022-10-12 15:20 UTC, closed without merging

2022-10-12 15:22 UTC, Osanchez commented
understood. well, if anyone is interested they can fork and build for themselves