Add "alone time until stop"
jagrosh/MusicBot pull request #583
Opened 2021-01-13 01:03 UTC by MichailiK

### This pull request...
  - [ ] Fixes a bug
  - [x] Introduces a new feature
  - [ ] Improves an existing feature
  - [ ] Boosts code quality or performance

### Description
This PR adds an incredibly-super-badly-oh-my-god-why-isnt-this-in-the-bot-yet feature, which allows the bot owner to configure, when the bot automatically leaves the voice channel when there is no one undeafened* is in the channel.

*Since you can only use music commands when listening (not deafened), I have applied the same logic to this feature.

### Purpose
Bandwidth, bandwidth & the bot just staying around there for no reason & it being slightly annoying to stop manually all the time.

### Relevant Issue(s)
Nothing except for a dozen of wishes of this feature

2021-02-08 08:14 UTC, UnrealValentin commented
You forgot following reason: Youtuber rate limitations ;)

2021-02-09 13:59 UTC, jagrosh requested changes

2021-02-09 14:22 UTC, jagrosh requested changes

2021-02-09 14:22 UTC, jagrosh commented on src/main/java/com/jagrosh/jmusicbot/audio/AloneInVoiceHandler.java
> +                        && x.getIdLong() != bot.getJDA().getSelfUser().getIdLong());
```suggestion
                        && !x.getUser().isBot());
```

2021-02-09 14:55 UTC, merged