Added seekto command
jagrosh/MusicBot pull request #910
Opened 2021-09-24 14:30 UTC by smogenheimer

### This pull request...
adds a command: "seekto" to seek to a specific position in the currently song.

2021-09-25 09:30 UTC, CyberFlameGO commented
Doesn't #674 have this as W.I.P already anyways?

2021-09-26 06:13 UTC, lokha commented
The code does not compile

```
[ERROR] /F:/IdeaProjects/MusicBot-seek/src/main/java/com/jagrosh/jmusicbot/JMusicBot.java:[119,43] ')' expected
[ERROR] /F:/IdeaProjects/MusicBot-seek/src/main/java/com/jagrosh/jmusicbot/JMusicBot.java:[120,43] ';' expected
```

2021-09-26 08:25 UTC, Sanduhr32 requested changes
:/

2021-09-26 08:25 UTC, Sanduhr32 commented on src/main/java/com/jagrosh/jmusicbot/JMusicBot.java
> +                        new SeekToCmd(bot);
Needs to be a `,`, not a semi colon `;`.

2021-09-26 08:25 UTC, Sanduhr32 commented on src/main/java/com/jagrosh/jmusicbot/commands/dj/SeekToCmd.java
> +                throw new NumberFormatException("Wrong format. Example: 5:18 (up to hours only).");
Should not fail, arithmetically divide the number into hours, minutes, etc.

If you wanted it to fail, use IllegalArgumentException.
NumberFormatException is for stuff like "0b7f" on binary, "3F" on dec,  or "0xGGCZ" on hex.

2021-10-04 09:17 UTC, MichailiK commented
#674 already exists, which is mostly done & polished.

2022-07-13 08:24 UTC, MichailiK commented
Since my PR #674 is (mostly) finished, I'll close this in favor of it.

2022-07-13 08:24 UTC, closed without merging