Voice channel mention
jagrosh/MusicBot pull request #932
Opened 2021-09-28 17:17 UTC by yo-louk

### This pull request...
  - [ ] Fixes a bug
  - [ ] Introduces a new feature
  - [x] Improves an existing feature
  - [ ] Boosts code quality or performance

### Description
I recently noticed voice channels can be mentioned just like text channels. A small change to the code to implement this feature.

![image](https://user-images.githubusercontent.com/64579257/135133671-409bf147-7a60-440d-9548-697e4c044ad1.png)
The top example is the current way the bot would mention a channel, the bottom is what I wish it would look like.
This my first pull request.

### Purpose
Aesthetics, ease of use. Clicking on the mentioned channel will automatically connect you to it.

2021-09-29 23:23 UTC, MichailiK requested changes
JDA offers a method to get a channel's mention string. Use that method instead.

2021-09-29 23:23 UTC, MichailiK commented on src/main/java/com/jagrosh/jmusicbot/commands/MusicCommand.java
> +                event.replyError("You must be listening in "+(current==null ? "a voice channel" : "<#"+current.getId()+">")+" to use that!");
```suggestion
                event.replyError("You must be listening in "+(current==null ? "a voice channel" : current.getAsMention())+" to use that!");
```

2021-09-29 23:23 UTC, MichailiK commented on src/main/java/com/jagrosh/jmusicbot/commands/MusicCommand.java
> +                    event.reply(event.getClient().getError()+" I am unable to connect to <#"+userState.getChannel().getId()+">!");
```suggestion
                    event.reply(event.getClient().getError()+" I am unable to connect to "+userState.getChannel().getAsMention()+"!");
```

2021-09-29 23:23 UTC, MichailiK commented on src/main/java/com/jagrosh/jmusicbot/commands/admin/SetvcCmd.java
> +                event.reply(event.getClient().getSuccess()+" Music can now only be played in <@"+list.get(0).getId()+">");
```suggestion
                event.reply(event.getClient().getSuccess()+" Music can now only be played in "+list.get(0).getAsMention());
```

2021-09-29 23:34 UTC, MichailiK commented
Additionally, my IDE has found another 3 usages that you've missed:

https://github.com/jagrosh/MusicBot/blob/b83028fb97318825c7adaa12caa4a3b94513c652/src/main/java/com/jagrosh/jmusicbot/audio/AudioHandler.java#L205

https://github.com/jagrosh/MusicBot/blob/b83028fb97318825c7adaa12caa4a3b94513c652/src/main/java/com/jagrosh/jmusicbot/commands/general/SettingsCmd.java#L60

https://github.com/jagrosh/MusicBot/blob/b83028fb97318825c7adaa12caa4a3b94513c652/src/main/java/com/jagrosh/jmusicbot/utils/FormatUtil.java#L77

Update these accordingly.

2021-10-01 18:50 UTC, yo-louk commented
Thanks for the elaborate feedback.
I agree with `getAsMention()` being more appropriate than `"<#"+vc.getId()+">"`.
I also applied these changes to the 3 other usages that I had missed earlier.

After successfully compiling the project, I ran the commands and got some good results, a few of which you can see below:

![image](https://user-images.githubusercontent.com/64579257/135671823-8e2138c8-ebee-456f-bcac-6189ba28352c.png)

2021-10-01 18:54 UTC, MichailiK approved these changes
Looks good! @jagrosh will have to take another look & merge if everything looks good.

2021-10-02 19:17 UTC, merged